### ISSUE TITLE
3 issues after I did the installation and run the command " npm run test"

### ISSUE THREAD

**Issue by wangmzdl** [ibm-watson-iot/iot-nodejs#37]
1) IotfGateway .connect() "after each" hook for "should throw an error if instantiated without config":
     TypeError: Cannot read property 'call' of undefined
      at callFn (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runnable.js:326:20)
      at Hook.Runnable.run (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runnable.js:319:7)
      at next (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:298:10)
      at Immediate.<anonymous> (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:320:5)

  2) IotfGateway .connect() Uncaught error outside test suite:
     Uncaught TypeError: Cannot read property 'currentRetry' of undefined
      at D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:531:27
      at Runner.runTest (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:424:5)
      at D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:528:12
      at next (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:342:14)
      at D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:352:7
      at next (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:284:14)
      at Immediate.<anonymous> (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:320:5)

  3) IotfGateway .connect() "after each" hook for "should throw an error if instantiated without config":
     TypeError: Cannot read property 'call' of undefined
      at callFn (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runnable.js:326:20)
      at Hook.Runnable.run (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runnable.js:319:7)
      at next (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:298:10)
      at Immediate.<anonymous> (D:\IdeaProjects\sensor\iot-nodejs\node_modules\mocha\lib\runner.js:320:5)

**Comment by jeffdare** [comment]
Hey @wangmzdl 
I just ran the tests that are present in this repo, it seem to run correctly. 

Did you write a new test? As the .connect() function does not have "config". This was a test for the constructor.

**Comment by amitmangalvedkar** [comment]
Closing the issue as there is no further response.
